spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: "1.0"
cards:
  message: "Welcome to the Eazy Bank cards related to APIs"
  contactDetails:
    name: "Tino Weber - Product Owner for Cards"
    email: "tino.weber@test.com"
  onCallSupport:
    - (222)222-1115
    - (222)222-1116

