FROM openjdk:17-jdk-slim

LABEL author="Solomon Hykes"

LABEL version="1.0"

LABEL web-site="http://www.test.com"

COPY target/accounts-0.0.1-SNAPSHOT.jar accounts-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","accounts-0.0.1-SNAPSHOT.jar"]