server:
  port: 8090
spring:
  application:
    name: loans
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "qa"
build:
  version: "3.0"
loans:
  message: "Welcome to Eazy Bank loans related to APIs"
  contactDetails:
    name: "Dina Dom - Developer"
    email: "dina.dom@test.com"
  onCallSupport:
    - (333)333-1111
    - (333)333-1112