server:
 port: 8090
spring:
 application:
  name: loans
 profiles:
  active: "prod"
 datasource:
  url: jdbc:mysql://192.168.186.128:6306/loansdb
  username: loans
  password: password
 jpa:
  show-sql: true
 sql:
  init:
   mode: always
 config:
  import: "optional:configserver:http://localhost:8071/"

management:
 endpoints:
  web:
   exposure:
    include: "*"