server:
 port: 8090
spring:
 application:
  name: loans
 profiles:
  active: "prod"
 datasource:
  url: jdbc:mysql://192.168.186.128:6306/loansdb
  username: loans
  password: password
 jpa:
  show-sql: true
 sql:
  init:
   mode: always
 config:
  import: "optional:configserver:http://localhost:8071/"
 metrics:
  tags:
   application: ${spring.application.name}

management:
 endpoints:
  web:
   exposure:
    include: "*"
 health:
  readiness-status:
   enabled: true
  liveness-status:
   enabled: true
 endpoint:
  shutdown:
   enabled: true
  health:
   probes:
    enabled: true
 info:
  env:
   enabled: true

eureka:
 instance:
  preferIpAddress: true
 client:
  fetchRegistry: true
  registerWithEureka: true
  serviceUrl:
   defaultZone: http://localhost:8070/eureka/

info:
 app:
  name: "loans"
  description: "Eazy Bank Loans Application"
  version: "1.0.0"

logging:
 level:
  com:
   eazybytes:
    loans: DEBUG
 pattern:
  level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"