services:
  network-deploy-service:
    networks:
      - eazybank

  microservice-db-config:
    extends:
      service: network-deploy-service
    image: mysql:8-oracle
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","localhost" ]
      interval: 80s
      timeout: 30s
      retries: 5
      start_period: 120s
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: qa
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
