build:
  version: "1.0"
accounts:
  message: "Welcome to the Eazy Bank APIs related to production environment!"
  contactDetails:
    name: "Dennis Rodman - Product Owner"
    email: "dennis.rodman@test.com"
  onCallSupport:
    - (111)111-2224
    - (111)111-2225