build:
  version: "2.0"
cards:
  message: "Welcome to the Eazy Bank cards related to QA APIs"
  contactDetails:
    name: "Jamie Lars - Cards QA"
    email: "jamie.lars@test.com"
  onCallSupport:
    - (222)222-1113
    - (222)222-1114

