build:
  version: "3.0"
loans:
  message: "Welcome to Eazy Bank loans related to APIs"
  contactDetails:
    name: "Dina Dom - Developer"
    email: "dina.dom@test.com"
  onCallSupport:
    - (333)333-1111
    - (333)333-1112