spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: "2.0"

accounts:
  message: "Welcome to the Eazy Bank APIs for the QA environment"
  contactDetails:
    name: "Henry Ford - QA Team"
    email: "henry.ford@test.com"
  onCallSupport:
    - (111)111-2226
    - (111)111-2227
