services:
  accountsdb:
    image: mysql:8-oracle
    container_name: "accountsdb"
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: accountsdb
      MYSQL_USER: accounts
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
    image: mysql:8-oracle
    container_name: cardsdb
    ports:
      - "5306:3306"
    environment:
      MYSQL_DATABASE: cardsdb
      MYSQL_USER: cards
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
    image: mysql:8-oracle
    container_name: loansdb
    ports:
      - "6306:3306"
    environment:
      MYSQL_DATABASE: loansdb
      MYSQL_USER: loans
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: solomonhykes/configserver:s8
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 80s
      timeout: 30s
      retries: 5
      start_period: 120s
    extends:
      file: common-config.yml
      service: microservice-base-config
  
  eurekaserver:
    image: solomonhykes/eurekaserver:s8
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 80s
      timeout: 30s
      retries: 5
      start_period: 120s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
  
  accounts:
    image: "solomonhykes/accounts:s8"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    depends_on:
      accountsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: jdbc:mysql://accountsdb:3306/accountsdb
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: "solomonhykes/cards:s8"
    container_name: "cards-ms"
    ports:
      - "9000:9000"
    depends_on:
      cardsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: jdbc:mysql://cardsdb:3306/cardsdb
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: "solomonhykes/loans:s8"
    container_name: "loans-ms"
    ports:
      - "8090:8090"
    depends_on:
      loansdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: jdbc:mysql://loansdb:3306/loansdb
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans1:
    image: "solomonhykes/loans:s8"
    container_name: "loans1-ms"
    ports:
      - "8091:8090"
    depends_on:
      loansdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: jdbc:mysql://loansdb:3306/loansdb
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  eazybank:
    driver: "bridge"