spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///C:/test/config"
        git:
          uri: "https://github.com/solomonhykes/banking-ms-config.git"
          default-label: main
          clone-on-start: true
          timeout: 5
          force-pull: true
  rabbitmq:
    host: "192.168.186.128"
    port: 5672
    username: "guest"
    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8071
encrypt:
  key: dLk0AGDNu3cJIG75N+RdliF96tPVcXKSqOuZdbr+X5s=
logging:
  level:
    org.springframework.cloud.config.server: DEBUG